name = input("Enter name")
print(f"welcome {name} To coding school")
num1 = int(input("Enter first number:"))
num2 = int(input("Enter second number:"))
print(f"sum of {num1} and {num2} is {num1+num2}")
print(f"subtraction of {num1} and {num2} is {num1-num2}")
print(f"multiplication of {num1} and {num2} is {num1*num2}")
print(f"division of {num1} and {num2} is {num1/num2}")  
print(f"modulus of {num1} and {num2} is {num1%num2}")